services:
  postgres:
    image: postgres:16.2
    platform: linux/x86_64
    ports:
      - 5432:5432
    env_file: ../.env
    volumes:
      - go-sqlc-postgres-sample-db-store:/var/lib/postgresql/data

volumes:
  go-sqlc-postgres-sample-db-store:
